from enum import Enum


class CargoesCreateErrorsErrorReason(str, Enum):

    INVALID_STATE = "INVALID_STATE"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    WAREHOUSE_LIMITS_EXCEED = "WAREHOUSE_LIMITS_EXCEED"
    SUPPLY_NOT_BELONG_CONTRACTOR = "SUPPLY_NOT_BELONG_CONTRACTOR"
    SUPPLY_NOT_BELONG_COMPANY = "SUPPLY_NOT_BELONG_COMPANY"
    IS_FINALIZED = "IS_FINALIZED"
    SKU_DISTRIBUTION_DISABLED = "SKU_DISTRIBUTION_DISABLED"
    SUPPLY_IS_NOT_EMPTY = "SUPPLY_IS_NOT_EMPTY"
    OPERATION_NOT_FOUND = "OPERATION_NOT_FOUND"
    OPERATION_FAILED = "OPERATION_FAILED"
