from enum import Enum


class DraftGetWarehouseFboListResponseWarehouseType(str, Enum):

    WAREHOUSE_TYPE_DELIVERY_POINT = "WAREHOUSE_TYPE_DELIVERY_POINT"
    WAREHOUSE_TYPE_ORDERS_RECEIVING_POINT = "WAREHOUSE_TYPE_ORDERS_RECEIVING_POINT"
    WAREHOUSE_TYPE_SORTING_CENTER = "WAREHOUSE_TYPE_SORTING_CENTER"
    WAREHOUSE_TYPE_FULL_FILLMENT = "WAREHOUSE_TYPE_FULL_FILLMENT"
    WAREHOUSE_TYPE_CROSS_DOCK = "WAREHOUSE_TYPE_CROSS_DOCK"
