from enum import Enum


class ErrorErrorLevel(str, Enum):

    ERROR_LEVEL_UNSPECIFIED = "ERROR_LEVEL_UNSPECIFIED"
    ERROR_LEVEL_ERROR = "ERROR_LEVEL_ERROR"
    ERROR_LEVEL_WARNING = "ERROR_LEVEL_WARNING"
    ERROR_LEVEL_INTERNAL = "ERROR_LEVEL_INTERNAL"
