from enum import Enum


class ItemValidationErrorType(str, Enum):

    SUPPLY_ITEM_NOT_FOUND = "SUPPLY_ITEM_NOT_FOUND"
    DUPLICATED_SUPPLY_ITEM = "DUPLICATED_SUPPLY_ITEM"
    BEFORE_DEADLINE = "BEFORE_DEADLINE"
    SAME_BARCODES = "SAME_BARCODES"
    SAME_ARTICLES = "SAME_ARTICLES"
    NOT_UNIQUE_SKU_BY_PRODUCT = "NOT_UNIQUE_SKU_BY_PRODUCT"
    QUANTITY_NOT_DIVISIBLE_BY_QUANT = "QUANTITY_NOT_DIVISIBLE_BY_QUANT"
    NOT_SINGLE_PALLET_SKU_IN_PALLET_CARGO = "NOT_SINGLE_PALLET_SKU_IN_PALLET_CARGO"
    NOT_ONE_QUANT_PALLET_SKU = "NOT_ONE_QUANT_PALLET_SKU"
    NOT_ECONOM_SKU = "NOT_ECONOM_SKU"
    QUANTITY_LESS_ONE = "QUANTITY_LESS_ONE"
    SUPPLY_ITEM_WITH_QUANT_NOT_FOUND = "SUPPLY_ITEM_WITH_QUANT_NOT_FOUND"
