from enum import Enum


class PriceIndexesColorIndex(str, Enum):

    COLOR_INDEX_UNSPECIFIED = "COLOR_INDEX_UNSPECIFIED"
    COLOR_INDEX_WITHOUT_INDEX = "COLOR_INDEX_WITHOUT_INDEX"
    COLOR_INDEX_GREEN = "COLOR_INDEX_GREEN"
    COLOR_INDEX_YELLOW = "COLOR_INDEX_YELLOW"
    COLOR_INDEX_RED = "COLOR_INDEX_RED"
