from enum import Enum


class SupplyOrderCancelStatusResponseCancelOrderError(str, Enum):

    INVALID_ORDER_STATE = "INVALID_ORDER_STATE"
    ORDER_IS_VIRTUAL = "ORDER_IS_VIRTUAL"
    ORDER_DOES_NOT_BELONG_TO_CONTRACTOR = "ORDER_DOES_NOT_BELONG_TO_CONTRACTOR"
    ORDER_DOES_NOT_BELONG_TO_COMPANY = "ORDER_DOES_NOT_BELONG_TO_COMPANY"
    OTHER_ASYNCHRONOUS_OPERATION_IN_PROGRESS = "OTHER_ASYNCHRONOUS_OPERATION_IN_PROGRESS"
