from enum import Enum


class V1bundleItemShipmentType(str, Enum):

    BUNDLE_ITEM_SHIPMENT_TYPE_GENERAL = "BUNDLE_ITEM_SHIPMENT_TYPE_GENERAL"
    BUNDLE_ITEM_SHIPMENT_TYPE_BOX = "BUNDLE_ITEM_SHIPMENT_TYPE_BOX"
    BUNDLE_ITEM_SHIPMENT_TYPE_PALLET = "BUNDLE_ITEM_SHIPMENT_TYPE_PALLET"
