from enum import Enum


class V1cargoesDeleteStatusResponseErrorSupplyErrorReasonEnum(str, Enum):

    SUPPLY_NOT_FOUND = "SUPPLY_NOT_FOUND"
    CANT_DELETE_ALL_CARGOES = "CANT_DELETE_ALL_CARGOES"
    SUPPLY_DOES_NOT_BELONG_TO_THE_CONTRACTOR = "SUPPLY_DOES_NOT_BELONG_TO_THE_CONTRACTOR"
    SUPPLY_DOES_NOT_BELONG_TO_THE_COMPANY = "SUPPLY_DOES_NOT_BELONG_TO_THE_COMPANY"
    SUPPLY_CARGOES_IS_FINALIZED = "SUPPLY_CARGOES_IS_FINALIZED"
    SUPPLY_CARGOES_LOCKED = "SUPPLY_CARGOES_LOCKED"
    OPERATION_NOT_FOUND = "OPERATION_NOT_FOUND"
