from enum import Enum


class V1cargoesLabelCreateErrorsErrorReason(str, Enum):

    INVALID_STATE = "INVALID_STATE"
    OPERATION_NOT_FOUND = "OPERATION_NOT_FOUND"
    OPERATION_FAILED = "OPERATION_FAILED"
    SUPPLY_NOT_BELONG_CONTRACTOR = "SUPPLY_NOT_BELONG_CONTRACTOR"
    SUPPLY_NOT_BELONG_COMPANY = "SUPPLY_NOT_BELONG_COMPANY"
    SUPPLY_IS_EMPTY = "SUPPLY_IS_EMPTY"
    CARGOES_NOT_FOUND = "CARGOES_NOT_FOUND"
