from enum import Enum


class V1calculationStatus(str, Enum):

    CALCULATION_STATUS_FAILED = "CALCULATION_STATUS_FAILED"
    CALCULATION_STATUS_SUCCESS = "CALCULATION_STATUS_SUCCESS"
    CALCULATION_STATUS_IN_PROGRESS = "CALCULATION_STATUS_IN_PROGRESS"
    CALCULATION_STATUS_EXPIRED = "CALCULATION_STATUS_EXPIRED"
