from enum import Enum


class V1itemSfboAttribute(str, Enum):

    ITEM_SFBO_ATTRIBUTE_NONE = "ITEM_SFBO_ATTRIBUTE_NONE"
    ITEM_SFBO_ATTRIBUTE_SUPER_FBO = "ITEM_SFBO_ATTRIBUTE_SUPER_FBO"
    ITEM_SFBO_ATTRIBUTE_ANTI_FBO = "ITEM_SFBO_ATTRIBUTE_ANTI_FBO"
