from enum import Enum


class V1setVehicleError(str, Enum):

    SET_VEHICLE_ERROR_UNSPECIFIED = "SET_VEHICLE_ERROR_UNSPECIFIED"
    SET_VEHICLE_ERROR_INVALID_ORDER_STATE = "SET_VEHICLE_ERROR_INVALID_ORDER_STATE"
    SET_VEHICLE_ERROR_VEHICLE_NOT_REQUIRED = "SET_VEHICLE_ERROR_VEHICLE_NOT_REQUIRED"
    SET_VEHICLE_ERROR_ORDER_NOT_BELONG_CONTRACTOR = "SET_VEHICLE_ERROR_ORDER_NOT_BELONG_CONTRACTOR"
    SET_VEHICLE_ERROR_ORDER_NOT_BELONG_COMPANY = "SET_VEHICLE_ERROR_ORDER_NOT_BELONG_COMPANY"
