from enum import Enum


class V1supplyOrderContentUpdateStatusResponseErrorEnum(str, Enum):

    INVALID_DRAFT_BUNDLE_ID = "INVALID_DRAFT_BUNDLE_ID"
    SOME_SERVICE_ERROR = "SOME_SERVICE_ERROR"
    HAS_UTD = "HAS_UTD"
    ORDER_SKU_LIMIT = "ORDER_SKU_LIMIT"
    SAME_SKU = "SAME_SKU"
    SUPPLY_LOCKED = "SUPPLY_LOCKED"
    INBOUND_NO_CAPACITY = "INBOUND_NO_CAPACITY"
    INBOUND_LOCK = "INBOUND_LOCK"
    SUPPLY_CONTENT_NOT_VALID = "SUPPLY_CONTENT_NOT_VALID"
    SUPPLY_BELONG_TO_ANOTHER_CONTRACTOR = "SUPPLY_BELONG_TO_ANOTHER_CONTRACTOR"
    SUPPLY_BELONG_TO_ANOTHER_COMPANY = "SUPPLY_BELONG_TO_ANOTHER_COMPANY"
    INCORRECT_SUPPLY_STATE = "INCORRECT_SUPPLY_STATE"
    INCORRECT_SUPPLY_SOURCE = "INCORRECT_SUPPLY_SOURCE"
    INCORRECT_STORAGE_WAREHOUSE = "INCORRECT_STORAGE_WAREHOUSE"
    DEADLINE = "DEADLINE"
    INACTIVE_CONTRACT = "INACTIVE_CONTRACT"
    QUANTITY_OUT_OF_RANGE_BOTTOM = "QUANTITY_OUT_OF_RANGE_BOTTOM"
    QUANTITY_OUT_OF_RANGE_UPPER = "QUANTITY_OUT_OF_RANGE_UPPER"
    EMPTY_CONTENT = "EMPTY_CONTENT"
    NO_SUPPLY_PRODUCT_BUNDLE_ID = "NO_SUPPLY_PRODUCT_BUNDLE_ID"
    ONLY_DOCLESS_ALLOWED = "ONLY_DOCLESS_ALLOWED"
    INVALID_VOLUME = "INVALID_VOLUME"
    SUPPLY_IS_VIRTUAL = "SUPPLY_IS_VIRTUAL"
    ORDER_LOCKED = "ORDER_LOCKED"
