from enum import Enum


class V1updateTimeslotError(str, Enum):

    UPDATE_TIMESLOT_ERROR_UNSPECIFIED = "UPDATE_TIMESLOT_ERROR_UNSPECIFIED"
    UPDATE_TIMESLOT_ERROR_INVALID_ORDER_STATE = "UPDATE_TIMESLOT_ERROR_INVALID_ORDER_STATE"
    UPDATE_TIMESLOT_ERROR_INCOMPATIBLE_ORDER_FLOW = "UPDATE_TIMESLOT_ERROR_INCOMPATIBLE_ORDER_FLOW"
    UPDATE_TIMESLOT_ERROR_SET_TIMESLOT_DEADLINE_EXCEED = "UPDATE_TIMESLOT_ERROR_SET_TIMESLOT_DEADLINE_EXCEED"
    UPDATE_TIMESLOT_ERROR_OUT_OF_ALLOWED_RANGE = "UPDATE_TIMESLOT_ERROR_OUT_OF_ALLOWED_RANGE"
    UPDATE_TIMESLOT_ERROR_ORDER_NOT_BELONG_CONTRACTOR = "UPDATE_TIMESLOT_ERROR_ORDER_NOT_BELONG_CONTRACTOR"
    UPDATE_TIMESLOT_ERROR_ORDER_NOT_BELONG_COMPANY = "UPDATE_TIMESLOT_ERROR_ORDER_NOT_BELONG_COMPANY"
