from enum import Enum


class V1warehouseScoringInvalidReason(str, Enum):

    WAREHOUSE_SCORING_INVALID_REASON_PARTIAL_MATRIX_AVAILABLE = (
        "WAREHOUSE_SCORING_INVALID_REASON_PARTIAL_MATRIX_AVAILABLE"
    )
    WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_MATRIX = "WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_MATRIX"
    WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_RANK = "WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_RANK"
    WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_ROUTE = "WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_ROUTE"
    WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_TIMESLOT_FOR_DROP_OFF_POINT = (
        "WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_TIMESLOT_FOR_DROP_OFF_POINT"
    )
    WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_TIMESLOT_FOR_STORAGE_WAREHOUSE = (
        "WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_TIMESLOT_FOR_STORAGE_WAREHOUSE"
    )
    WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_TIMESLOT_FOR_BOTH_WAREHOUSE = (
        "WAREHOUSE_SCORING_INVALID_REASON_NOT_AVAILABLE_TIMESLOT_FOR_BOTH_WAREHOUSE"
    )
