from enum import Enum


class V1warehouseScoringStatus(str, Enum):

    WAREHOUSE_SCORING_STATUS_FULL_AVAILABLE = "WAREHOUSE_SCORING_STATUS_FULL_AVAILABLE"
    WAREHOUSE_SCORING_STATUS_PARTIAL_AVAILABLE = "WAREHOUSE_SCORING_STATUS_PARTIAL_AVAILABLE"
    WAREHOUSE_SCORING_STATUS_NOT_AVAILABLE = "WAREHOUSE_SCORING_STATUS_NOT_AVAILABLE"
