from enum import Enum


class V2supplyState(str, Enum):

    SUPPLY_STATE_UNSPECIFIED = "SUPPLY_STATE_UNSPECIFIED"
    SUPPLY_STATE_DATA_FILLING = "SUPPLY_STATE_DATA_FILLING"
    SUPPLY_STATE_READY_TO_SUPPLY = "SUPPLY_STATE_READY_TO_SUPPLY"
    SUPPLY_STATE_ACCEPTED_AT_SUPPLY_WAREHOUSE = "SUPPLY_STATE_ACCEPTED_AT_SUPPLY_WAREHOUSE"
    SUPPLY_STATE_IN_TRANSIT = "SUPPLY_STATE_IN_TRANSIT"
    SUPPLY_STATE_ACCEPTANCE_AT_STORAGE_WAREHOUSE = "SUPPLY_STATE_ACCEPTANCE_AT_STORAGE_WAREHOUSE"
    SUPPLY_STATE_REPORTS_CONFIRMATION_AWAITING = "SUPPLY_STATE_REPORTS_CONFIRMATION_AWAITING"
    SUPPLY_STATE_REPORT_REJECTED = "SUPPLY_STATE_REPORT_REJECTED"
    SUPPLY_STATE_COMPLETED = "SUPPLY_STATE_COMPLETED"
    SUPPLY_STATE_REJECTED_AT_SUPPLY_WAREHOUSE = "SUPPLY_STATE_REJECTED_AT_SUPPLY_WAREHOUSE"
    SUPPLY_STATE_CANCELLED = "SUPPLY_STATE_CANCELLED"
    SUPPLY_STATE_OVERDUE = "SUPPLY_STATE_OVERDUE"
